CREATE TABLE CONTINENTS(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   POPULATION     INT     NOT NULL,
   AREA           FLOAT NOT NULL
);

CREATE TABLE COUNTRIES(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   POPULATION     INT     NOT NULL,
   AREA           FLOAT   NOT NULL,
   TOTAL_HOSPITALS INT    NOT NULL,
   TOTAL_NATIONAL_PARKS INT NOT NULL
);

CREATE TABLE CITIES(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   POPULATION     INT     NOT NULL,
   AREA           FLOAT   NOT NULL,
   TOTAL_ROADS    INT     NOT NULL,
   TOTAL_TREES    INT     NOT NULL
);
